In [1]:
import pandas as pd
from label_util import LabelingTool
import os

In [2]:
#читаем ваш датафрейс
df = pd.read_csv('alina.csv')
df = df.set_index('wordnet_id')

In [3]:
df

,subset,core_synset,core_lemma,hypernym_synsets,cohyponym_synsets,wikimedia_images,image_filename,definition,model_a,model_b
wordnet_id,,,,,,,,,,
13388245,appendix,coin.n.01,coin,['coinage.n.01'],['coin.n.01'],['https://upload.wikimedia.org/wikipedia/commo...,"India, Kushan, Vasudeva II, 3rd century - Coin...",a flat metal piece (usually a disc) used as money,playgroundai_playground-v2.5-1024px-aesthetic,retrieval
13389105,appendix,bawbee.n.01,bawbee,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Mary bawbee 1542 127326.jpg,an old Scottish coin of little value,runwayml_stable-diffusion-v1-5,stabilityai_stable-diffusion-xl-base-1.0
13389194,appendix,bezant.n.01,bezant,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Crusader coins of the Kingdom of Jerusalem.jpg,a gold coin of the Byzantine Empire; widely ci...,PixArt-alpha_PixArt-Sigma-XL-2-512-MS,runwayml_stable-diffusion-v1-5
13388111,appendix,change.n.08,change,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Change in Average Temperature With Fahrenheit.svg,coins of small denomination regarded collectively,DeepFloyd_IF-I-XL-v1.0,kandinsky-community_kandinsky-3
13389864,appendix,crown.n.06,crown,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,서봉총 금관 금제드리개.jpg,an English coin worth 5 shillings,retrieval,DeepFloyd_IF-I-XL-v1.0
...,...,...,...,...,...,...,...,...,...,...
74157104,predict_hypernym,oldster.n.01,oldster,['adult.n.01'],"['brachycephalic.n.01', 'caregiver.n.02', 'cat...",['https://upload.wikimedia.org/wikipedia/commo...,Старик (oldster) (50904206177).jpg,an elderly person,Tencent-Hunyuan_HunyuanDiT-v1.2-Diffusers,prompthero_openjourney
4514738,predict_hypernym,upper_deck.n.01,upper_deck,['deck.n.01'],"['afterdeck.n.01', 'flight_deck.n.01', 'forede...",['https://upload.wikimedia.org/wikipedia/commo...,Upper Deck Logo.svg,a higher deck,stabilityai_stable-diffusion-3-medium-diffusers,stabilityai_stable-diffusion-xl-base-1.0
14966192,simple_triplet_2parent,nylon.n.01,nylon,"['man-made_fiber.n.01', 'polyamide.n.01']","['acrylic_fiber.n.01', 'nylon.n.01']",['https://upload.wikimedia.org/wikipedia/commo...,Черные чулки.jpg,a thermoplastic polyamide; a family of strong ...,playgroundai_playground-v2.5-1024px-aesthetic,runwayml_stable-diffusion-v1-5
6474122,predict_hypernym,questionnaire.n.01,questionnaire,['form.n.08'],"['application_form.n.01', 'claim_form.n.01', '...",['https://upload.wikimedia.org/wikipedia/commo...,Questionnaire-checklist-completed.png,a form containing a set of questions; submitte...,stabilityai_sdxl-turbo,Tencent-Hunyuan_HunyuanDiT-v1.2-Diffusers
13931145,predict_hypernym,friendship.n.01,friendship,['relationship.n.03'],"['account.n.03', 'acquaintance.n.02', 'affilia...",['https://upload.wikimedia.org/wikipedia/commo...,Human–canine friendship - girl hugging her dog...,the state of being friends (or friendly),Tencent-Hunyuan_HunyuanDiT-v1.2-Diffusers,DeepFloyd_IF-I-XL-v1.0

In [3]:
#df = df.drop(columns=['assessor_vitya'])

In [4]:
labeler = LabelingTool(
    dataset=df,
    assessor_id='alina', # ваше имя 
    image_path='/home/data/v.moskvoretskii/taxo_demo_images/images', #путь до разархивированных картинок
    save2path='alina.csv', # куда сохранится
    img_type='.png', # не нужно, внутри пофикшено все
    ignore_all_labeled=True
    )

Labeling is stopped!

In [5]:
labeler.label_samples()

VBox(children=(HBox(children=(Output(), Output()), layout=Layout(align_items='center')), VBox(children=(Output…

In [6]:
df

,subset,core_synset,core_lemma,hypernym_synsets,cohyponym_synsets,wikimedia_images,image_filename,definition,model_a,model_b,assessor_vitya
wordnet_id,,,,,,,,,,,
5410315,predict_hypernym,gonadotropin.n.01,gonadotropin,['hormone.n.01'],"['adrenocorticotropic_hormone.n.01', 'adrenost...",['https://upload.wikimedia.org/wikipedia/commo...,Estrogen provocation test and gonadotropin sur...,hormone secreted by the anterior pituitary gla...,prompthero_openjourney,stabilityai_stable-diffusion-3-medium-diffusers,3.0
33877584,appendix_llama,coinage.n.01,numismatics,['currency.n.01'],"['cash.n.01', 'eurocurrency.n.01', 'hard_curre...",['https://upload.wikimedia.org/wikipedia/commo...,Coin collectors and enthusiasts by Yogabrata C...,coins collectively,prompthero_openjourney,stabilityai_sdxl-turbo,1.0
56250900,appendix_llama,coin.n.01,bee,['coinage.n.01'],[],['https://upload.wikimedia.org/wikipedia/commo...,Bee Collecting Pollen 2004-08-14.jpg,a flat metal piece (usually a disc) used as money,PixArt-alpha_PixArt-Sigma-XL-2-512-MS,DeepFloyd_IF-I-XL-v1.0,0.0
70890935,appendix_llama,coin.n.01,gold coin,['coinage.n.01'],[],['https://upload.wikimedia.org/wikipedia/commo...,"Gold coin of the Kushan empire, king Vasudeva ...",a flat metal piece (usually a disc) used as money,PixArt-alpha_PixArt-Sigma-XL-2-512-MS,retrieval,1.0
66203715,appendix_llama,coin.n.01,transformation,['coinage.n.01'],[],['https://upload.wikimedia.org/wikipedia/commo...,Bacterial Transformation.svg,a flat metal piece (usually a disc) used as money,stabilityai_stable-diffusion-xl-base-1.0,playgroundai_playground-v2.5-1024px-aesthetic,3.0
...,...,...,...,...,...,...,...,...,...,...,...
92219553,predict_hypernym_llama,activity.n.01,self-worship,['act.n.02'],"['acquiring.n.01', 'action.n.01', 'assumption....",['https://upload.wikimedia.org/wikipedia/commo...,2016 Bahai House of Worship Langenhain 1 ks01.jpg,any specific behavior,stabilityai_stable-diffusion-xl-base-1.0,prompthero_openjourney,NaN
65034633,predict_hypernym_llama,adult.n.01,oldster,['person.n.01'],"['abator.n.01', 'abjurer.n.01', 'abomination.n...",['https://upload.wikimedia.org/wikipedia/commo...,Старик (oldster) (50904206177).jpg,a fully developed person from maturity onward,stabilityai_stable-diffusion-xl-base-1.0,runwayml_stable-diffusion-v1-5,NaN
25851699,predict_hypernym_llama,deck.n.01,deck,['platform.n.01'],"['auction_block.n.01', 'bandstand.n.01', 'catw...",['https://upload.wikimedia.org/wikipedia/commo...,Bridge and deck of Gullbritt.jpg,any of various platforms built into a vessel,stabilityai_stable-diffusion-3-medium-diffusers,kandinsky-community_kandinsky-3,NaN
85363317,simple_triplet_2parent_llama,man-made_fiber.n.01,nylon,['fiber.n.01'],"['bassine.n.01', 'bristle.n.01', 'byssus.n.01'...",['https://upload.wikimedia.org/wikipedia/commo...,Черные чулки.jpg,fiber created from natural materials or by che...,DeepFloyd_IF-I-XL-v1.0,PixArt-alpha_PixArt-Sigma-XL-2-512-MS,NaN
41772405,predict_hypernym_llama,form.n.08,questionnaire,['document.n.01'],"['ballot.n.01', 'brevet.n.01', 'capitulation.n...",['https://upload.wikimedia.org/wikipedia/commo...,Questionnaire-checklist-completed.png,a printed document with spaces in which to write,stabilityai_stable-diffusion-xl-base-1.0,Tencent-Hunyuan_HunyuanDiT-v1.2-Diffusers,NaN

In [7]:
len(df.index[df['assessor_vitya'].notna()])

558

In [ ]:
output = pd.read_csv('alina.csv', index_col=0) # проверяем что все ок