In [90]:
import pandas as pd
from scipy.stats import spearmanr, pearsonr, kendalltau, PermutationMethod, MonteCarloMethod
import itertools

In [32]:
df = pd.read_csv('../data/labeling/test_output_ira_def.csv')

In [33]:
df

,wordnet_id,Unnamed: 0,subset,core_synset,core_lemma,hypernym_synsets,cohyponym_synsets,wikimedia_images,image_filename,definition,model_a,model_b,assessor_ira
0,14389754,2526,predict_hypernym_llama,relationship.n.03,friendship,['state.n.02'],"['action.n.02', 'being.n.01', 'cleavage.n.01',...",['https://upload.wikimedia.org/wikipedia/commo...,Human–canine friendship - girl hugging her dog...,a close and trusting relationship between two ...,prompthero_openjourney,retrieval,1
1,64348125,2527,predict_hypernym_llama,discolor.v.03,dye,['change.v.02'],"['acetylate.v.01', 'adjust.v.03', 'alkalinize....",['https://upload.wikimedia.org/wikipedia/commo...,Childhood Joy.jpg,a substance used to change the color of materi...,stabilityai_stable-diffusion-xl-base-1.0,prompthero_openjourney,0
2,44261072,2528,predict_hypernym_llama,nullification.n.02,rescission,['change_of_state.n.01'],"['aeration.n.02', 'arousal.n.01', 'beautificat...",['https://upload.wikimedia.org/wikipedia/commo...,Immediate rescission of rules regarding Ohio's...,the act of rescinding; cancellation or reversa...,playgroundai_playground-v2.5-1024px-aesthetic,stabilityai_sdxl-turbo,1
3,93157521,2529,predict_hypernym_llama,compete.v.01,hit,[],[],['https://upload.wikimedia.org/wikipedia/commo...,Harbin Institute of Technology - Main Bldg.jpg,"a successful or popular piece of work, especia...",kandinsky-community_kandinsky-3,runwayml_stable-diffusion-v1-5,3
4,34889612,2530,predict_hypernym_llama,sauce.n.01,vinaigrette,['condiment.n.01'],"['catsup.n.01', 'chili_sauce.n.01', 'chutney.n...",['https://upload.wikimedia.org/wikipedia/commo...,Raspberry vinaigrette.jpg,"A dressing made primarily of oil, vinegar, and...",stabilityai_stable-diffusion-3-medium-diffusers,stabilityai_stable-diffusion-xl-base-1.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
839,41796839,3365,leafs_and_no_leafs_llama,area.n.03,renal area,['body_part.n.01'],"['abdomen.n.01', 'adnexa.n.01', 'ambulacrum.n....",['https://upload.wikimedia.org/wikipedia/commo...,CT of sclerotic lesions in the skull in renal ...,The region in the human body located in the lo...,retrieval,stabilityai_stable-diffusion-xl-base-1.0,3
840,36389327,3366,predict_hypernym_llama,card_player.n.01,bridge player,['player.n.01'],"['ballplayer.n.01', 'billiard_player.n.01', 'b...",['https://upload.wikimedia.org/wikipedia/commo...,Kevin Collins (bridge player).jpg,a person who participates in the card game of ...,playgroundai_playground-v2.5-1024px-aesthetic,runwayml_stable-diffusion-v1-5,0
841,27347584,3367,predict_hypernym_llama,domestic_partner.n.01,married woman,['person.n.01'],"['abator.n.01', 'abjurer.n.01', 'abomination.n...",['https://upload.wikimedia.org/wikipedia/commo...,The Woman He Married (1922) - 4.jpg,a woman who has entered into the legal and soc...,kandinsky-community_kandinsky-3,stabilityai_sdxl-turbo,3
842,13967420,3368,predict_hypernym_llama,body_part.n.01,abdomen,['part.n.03'],"['acicula.n.01', 'base.n.04', 'corner.n.09', '...",['https://upload.wikimedia.org/wikipedia/commo...,Abdomen-periumbilical region.png,A part of the body that lies between the thora...,playgroundai_playground-v2.5-1024px-aesthetic,runwayml_stable-diffusion-v1-5,3
843,78890307,3369,predict_hypernym_llama,hormone.n.01,gonadotropin,['secretion.n.02'],"['autacoid.n.01', 'ganoin.n.01', 'intestinal_j...",['https://upload.wikimedia.org/wikipedia/commo...,Estrogen provocation test and gonadotropin sur...,a hormone produced by the anterior pituitary g...,runwayml_stable-diffusion-v1-5,playgroundai_playground-v2.5-1024px-aesthetic,3

In [34]:
df.columns

Index(['wordnet_id', 'Unnamed: 0', 'subset', 'core_synset', 'core_lemma',
       'hypernym_synsets', 'cohyponym_synsets', 'wikimedia_images',
       'image_filename', 'definition', 'model_a', 'model_b', 'assessor_ira'],
      dtype='object')

In [35]:
df.columns = ['wordnet_id', 'Unnamed: 0', 'subset', 'core_synset', 'core_lemma',
       'hypernym_synsets', 'cohyponym_synsets', 'wikimedia_images',
       'image_filename', 'definition', 'model_a', 'model_b', 'result']

In [36]:
df.to_csv('../data/labeling/test_output_ira_def.csv')

In [40]:
ira = pd.read_csv('../data/labeling/test_output_ira_def.csv_elo.csv')
vitya = pd.read_csv('../data/labeling/vitya_def.csv_elo.csv')
kate = pd.read_csv('../data/labeling/test_output_def_kate.csv_elo.csv')
alina = pd.read_csv('../data/labeling/alina_def.csv_elo.csv')

In [38]:
ira

,Unnamed: 0,results,model,score,lower,upper
0,0,"[1060.3949007094145, 1043.1725790517212, 1032....",stabilityai_stable-diffusion-xl-base-1.0,1043,1017,1072
1,1,"[1039.8801725708747, 1023.1949077109658, 1041....",kandinsky-community_kandinsky-3,1039,1008,1067
2,2,"[1040.4345049468911, 1047.5850043339774, 1069....",stabilityai_sdxl-turbo,1037,1004,1065
3,3,"[1017.2169568236874, 1013.2333487978136, 1044....",playgroundai_playground-v2.5-1024px-aesthetic,1034,1009,1060
4,4,"[1051.959248679348, 1037.1730420340284, 1024.9...",PixArt-alpha_PixArt-Sigma-XL-2-512-MS,1026,997,1047
5,5,"[989.5964668142792, 1002.6850567296336, 1012.8...",Tencent-Hunyuan_HunyuanDiT-v1.2-Diffusers,1004,973,1038
6,6,"[982.4171138008531, 1027.834389964525, 974.722...",retrieval,1001,966,1037
7,7,"[1008.2559817777399, 1002.3402735901437, 991.1...",DeepFloyd_IF-I-XL-v1.0,993,966,1024
8,8,"[974.5618128116613, 963.3518753188221, 965.340...",stabilityai_stable-diffusion-3-medium-diffusers,991,965,1023
9,9,"[918.6951258757988, 923.1044713721017, 943.442...",runwayml_stable-diffusion-v1-5,928,899,955
10,10,"[916.5877151894517, 916.3250510962674, 898.721...",prompthero_openjourney,900,864,930

In [44]:
spearmanr(ira['model'].values, vitya['model'].values)

SignificanceResult(statistic=-0.18181818181818182, pvalue=0.5926152128455)

In [77]:
merged = ira.merge(vitya, on='model', how='left', suffixes=('_ira', '_vitya'))
merged = ira.merge(vitya, on='model', how='left', suffixes=('_ira', '_vitya'))

merged = merged.merge(kate, on='model', how='left')

In [78]:
merged = merged.loc[:, ['model', 'score_ira', 'lower_ira', 'upper_ira', 'score_vitya', 'upper_vitya', 'lower_vitya', 'score', 'lower', 'upper']]

In [79]:
merged['score_alina'] = alina['score']
merged['lower_alina'] = alina['lower']
merged['upper_alina'] = alina['upper']

In [64]:
spearmanr(merged['lower_vitya'], merged['lower_ira'])

SignificanceResult(statistic=0.6712328767123288, pvalue=0.023738098608714602)

In [66]:
spearmanr(merged['lower_vitya'], merged['lower'])

SignificanceResult(statistic=0.7608220194556027, pvalue=0.006545082815417328)

In [67]:
spearmanr(merged['lower_vitya'], merged['lower_alina'])

SignificanceResult(statistic=0.6697056099399616, pvalue=0.024178155822074793)

In [69]:
merged[:,]

TypeError: bad operand type for unary -: 'str'

In [80]:
types = 'lower'
merged.drop(columns='model').corr()

,score_ira,lower_ira,upper_ira,score_vitya,upper_vitya,lower_vitya,score,lower,upper,score_alina,lower_alina,upper_alina
score_ira,1.000000,0.997465,0.996237,0.785307,0.763542,0.787236,0.741082,0.743865,0.753546,0.978892,0.977080,0.978949
lower_ira,0.997465,1.000000,0.991989,0.787647,0.766908,0.789513,0.757545,0.763645,0.767159,0.975508,0.976276,0.976073
upper_ira,0.996237,0.991989,1.000000,0.764683,0.742471,0.768335,0.708113,0.709421,0.719202,0.967384,0.963354,0.966343
score_vitya,0.785307,0.787647,0.764683,1.000000,0.994517,0.999284,0.745198,0.764485,0.763824,0.778210,0.794617,0.762251
upper_vitya,0.763542,0.766908,0.742471,0.994517,1.000000,0.991796,0.749649,0.767811,0.764133,0.752184,0.767886,0.742393
lower_vitya,0.787236,0.789513,0.768335,0.999284,0.991796,1.000000,0.732775,0.752648,0.751300,0.777285,0.793799,0.758915
score,0.741082,0.757545,0.708113,0.745198,0.749649,0.732775,1.000000,0.996204,0.996953,0.749729,0.770082,0.764816
lower,0.743865,0.763645,0.709421,0.764485,0.767811,0.752648,0.996204,1.000000,0.991478,0.744709,0.767112,0.759727
upper,0.753546,0.767159,0.719202,0.763824,0.764133,0.751300,0.996953,0.991478,1.000000,0.772871,0.792251,0.785604
score_alina,0.978892,0.975508,0.967384,0.778210,0.752184,0.777285,0.749729,0.744709,0.772871,1.000000,0.998476,0.995327
lower_alina,0.977080,0.976276,0.963354,0.794617,0.767886,0.793799,0.770082,0.767112,0.792251,0.998476,1.000000,0.991918
upper_alina,0.978949,0.976073,0.966343,0.762251,0.742393,0.758915,0.764816,0.759727,0.785604,0.995327,0.991918,1.000000

In [122]:
prefix = 'score'
scores_df = merged[[f'{prefix}_ira', f'{prefix}_vitya', prefix, f'{prefix}_alina']]

# Initialize lists to store results
results = []
columns = scores_df.columns

# Compute correlations and p-values between all pairs of scores
for col1, col2 in itertools.combinations(columns, 2):
    if col1 != col2:  # Exclude self-comparison
        corr, p_value = pearsonr(scores_df[col1].dropna(), scores_df[col2].dropna(), method=MonteCarloMethod(n_resamples=10000))
        results.append({'Assessor Pair': f'{col1} vs {col2}', 'Correlation': corr, 'P-Value': round(p_value, 4)})

# Convert results into a DataFrame
correlation_table = pd.DataFrame(results)

In [125]:
correlation_table

                Assessor Pair  Correlation  P-Value
0    score_ira vs score_vitya     0.785307   0.0038
1          score_ira vs score     0.741082   0.0106
2    score_ira vs score_alina     0.978892   0.0002
3        score_vitya vs score     0.745198   0.0066
4  score_vitya vs score_alina     0.778210   0.0054
5        score vs score_alina     0.749729   0.0068

In [124]:
correlation_table.to_csv('correlations.csv')